sudo: false
branches:
  only:
    - master
language: ruby
cache: bundler
rvm:
  - 2.1
  - 2.2

script: bundle exec rspec
before_script:
  - bundle exec rake app:db:create
  - bundle exec rake app:db:migrate
  - bundle exec rake app:db:test:prepare

